[programs.localnet]
coin98_gift = "ApYM2yphUQFpDK4TBPeZoQQ6krXZKTUvHe8MUbgjy4Ny"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
